### ISSUE TITLE
Links in the [[ ]] MediaWiki format aren't converted

### ISSUE THREAD

**Issue by timpaul** [NickColley/website-from-github-wiki#2]
Such a good idea - I've long suspected the GitHub wikis could be used like this, but couldn't fathom it!

Anyway, something that would be awesome is if the [[PageTitle]] MediaWiki syntax for links was recognised and converted.

Using the MediaWiki format in the GitHub wiki environment ensures that all internal links work, including in the sidebar and footer blocks. 

Unfortunately, they aren't converted in the build process. You can use standard markdown links instead, but these won't work for both the GitHub Wiki and GitHub Pages.

**Comment by NickColley** [comment]
I sort of handle relative links in this way but this is interesting, do you have an example where it does not work to do a relative link like `[Page](./Page)`?

Or is this more a 'support MediaWiki please'?

**Comment by timpaul** [comment]
Aha! I'd forgotten about './' - how embarrassing!

Yep - that seems to work just fine. I think the remaining issues are more ones of convenience:

For example, writing out link paths in full is comparatively fiddly:

<img width="356" alt="Image of GitHub interface showing MediaWiki and standard Markdown link formatting" src="https://user-images.githubusercontent.com/1590604/198070667-28574955-0560-493c-8f43-b0c72ac4814e.png">

Secondly, the MediaWiki format provides a really nice mechanism in the GitHub wiki interface for creating new pages, just by first creating the link to the non-existant page - then clicking on it. This doesn't work with standard markdown links.

Eg. Clicking the red link below will open the 'create new page' screen with the title prepopulated to the link text:

<img width="226" alt="Image of GitHub interface showing how MediaWiki links for nonexistant pages are treated" src="https://user-images.githubusercontent.com/1590604/198070998-4b7e8fa3-e0db-427c-acdb-53abd3061c35.png">

**Comment by NickColley** [comment]
I have brought over a bunch of transforms that I have used in a different project to get rendering as close to GitHub as possible.

And added a plugin that does what you want in the process:

https://github.com/NickColley/website-from-github-wiki/blob/cd17f2c23bd6d6cfceaa384f685f50f6a4ddce2d/.eleventy.config.cjs#L34-L49

So if you use the current build it'll work!
